hlxsites/prisma-cloud-docs-website

blocks/side-nav/side-nav.js
scripts/scripts.js

- update fetch in sidenav block to use multisheet query
- update metadata to use `book` and `additional-books`
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/admin-guide-pcee/welcome/welcome
- After: https://maxed-book-json--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/admin-guide-pcee/welcome/welcome

fix: use multisheet query for book sidenav json

---

scripts/scripts.js

the `-docs` repo is now correctly configured with loose CORs headers (`access-control-allow-origin: *`), this change is to use `hlx.page` as the preview origin instead of the worker directly

fix: use hlx.page for preview

---

.github/pull_request_template.md
scripts/scripts.js

Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/30-xx/admin-guide-pcee/install/install-defender/auto-defend-host
- After: https://maxed-path-fix--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/30-xx/admin-guide-pcee/install/install-defender/auto-defend-host

fix: use docs path prefix

---

blocks/procedure/procedure.css
styles/lazy-styles.css
styles/styles.css

Fallback font (generated with https://github.com/pixel-point/fontpie):
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/access-control/rbac
- After: https://fonts-swap--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/access-control/rbac

font display swap with fallback

---

prisma/prisma-cloud/blocks/article/article.js
prisma/prisma-cloud/blocks/sidenav/sidenav.css
prisma/prisma-cloud/blocks/sidenav/sidenav.js
prisma/prisma-cloud/scripts/scripts.js

Fix #49
- use `all-books` for name of metadata entry instead of `additional-books`, since it in fact includes all books
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/is-notifications/notifications/notifications
- After: https://maxed-fixes--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/is-notifications/notifications/notifications

hide versions selector on unversioned books, change book sheet

---

prisma/prisma-cloud/blocks/article/article.js
prisma/prisma-cloud/blocks/fragment/fragment.js
prisma/prisma-cloud/scripts/scripts.js

Fix #86 
Fix #60
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-accounts
- After: https://issue-86--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-accounts

bare includes, load issue

---

prisma/prisma-cloud/blocks/sidenav/sidenav.css

Fix #91 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/public-sector/release-findings/release-findings
- After: https://sidenav-active-link-color--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/public-sector/release-findings/release-findings

fix sidenav active link color (fixes #91)

---

prisma/prisma-cloud/blocks/breadcrumbs/breadcrumbs.css
prisma/prisma-cloud/scripts/scripts.js
prisma/prisma-cloud/styles/styles.css

* load breadcrumb earlier
* hide footer until main content is loaded
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/getting-started
- After: https://book-layout-shift--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/getting-started

fix: book page layout shift

---

prisma/prisma-cloud/blocks/article/article.js
prisma/prisma-cloud/blocks/sidenav/sidenav.js

- redirect to unversioned topic on 404, should exclude `not-applicable`
- single child link fix in sidenav, should use the child's href not the parent's
Fix #90
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/public-sector/release-findings/release-findings
- After: https://maxed-fixes--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/public-sector/release-findings/release-findings

various fixes

---

prisma/prisma-cloud/blocks/sidenav/sidenav.js

Fix #104
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/public-sector
- After: https://book-order--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/public-sector

fix: sidenav follow book order defined in metadata sheet

---

prisma/prisma-cloud/blocks/sidenav/sidenav.js
prisma/prisma-cloud/scripts/scripts.js

Fix #128
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/authentication/assign-roles
- After: https://maxed-128--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/authentication/assign-roles

fix: avoid overwriting state in pops, handle navigate events in sidenav

---

prisma/prisma-cloud/blocks/header/header.js

Fix #125
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-windows
- After: https://maxed-125--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-windows

fix(safari): use selector without nth-child for elements without parent

---

prisma/prisma-cloud/blocks/sidenav/sidenav.js
prisma/prisma-cloud/scripts/scripts.js
types/Events.d.ts

- wait for list expansion before scrolling sidenav item into view
- previously a race condition occasionally made the scroll not happen
- save initial state on article fetch for last popstate
- previously the first page visited in a new session could not be navigated to via "back" button
Fix #62
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/vulnerability-management/registry-scanning/scan-google-artifact-registry
- After: https://maxed-spa--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/vulnerability-management/registry-scanning/scan-google-artifact-registry

sidenav, spa loading fixes

---

prisma/prisma-cloud/blocks/fragment/fragment.js

Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-azure?branch=ian/fix-include
- After: https://maxed-fixes-2--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-azure?branch=ian/fix-include

fix: use docs origin for relative fragment paths

---

fstab.yaml

We'll publish all legacy books as a doc set, under the product key "classic".
Test URLs:
- After: https://ian-classic--prisma-cloud-docs-website--hlxsites.hlx.page/

Add legacy product/doc-set

---

fstab.yaml

These were being used for legacy books, but we decided to combine all legacy books into a single doc set.
Test URLs:
- After: https://ian-cleanup--prisma-cloud-docs-website--hlxsites.hlx.page/

Remove prisma-cloud-ag and prisma-cloud-rql-ref products

---

prisma/prisma-cloud/blocks/search-bar/search-bar.js

Per Request, Before search bar dropdown values were taken from meta tag 'product', as per the request changed metatag to 'docset-title'
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/use-cases/secure-the-infrastructure/gain-visibility-into-your-cloud-estate
- After: https://coveo-uat--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/use-cases/secure-the-infrastructure/gain-visibility-into-your-cloud-estate

PCDTUS-49: Fix entry in search drop-down menu

---

prisma/prisma-cloud/blocks/sidenav/sidenav.js

fix #163 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/connect-cloud-accounts
- After: https://maxed-bugs--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/connect-cloud-accounts

fix: use loadBook in sidenav, fix sidenav nesting bug

---

sitemap-index.xml

Remove unneeded sitemaps
fix #165
Test URLs:
- After: https://ian-fix-sitemap-index--prisma-cloud-docs-website--hlxsites.hlx.page/

Fix sitemap index

---

blocks/table/table.js
scripts/scripts.js
styles/styles.css

Fix #169
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/rn/known-issues/known-issues-on-pc
- After: https://maxed-inline-macro--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/rn/known-issues/known-issues-on-pc

fix: pill styling, allow within tds

---

blocks/table/table.js

- change worker output to provide colspans of all cells (unless they're all `1`)
- format: `<row1cell1>,<row1cell2>,...<row1cellN>;<row2cell1>,<row2cell2>,...<row2cellN>;<rowNcell1>,...<rowNcellN>`
- change table block to use those spans
ref: https://github.com/hlxsites/prisma-cloud-docs/pull/120
Fix #200
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/dashboards/dashboards-get-started
- After: https://maxed-tables--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/dashboards/dashboards-get-started

fix: allow colspans on any cell

---

blocks/card-carousel/card-carousel.css

Test URLs:
- After: https://ian-carousel-fix--prisma-cloud-docs-website--hlxsites.hlx.page/

fix: hide carousel overflow by default

---

blocks/article/article.js
blocks/sidenav/sidenav.js

Only some books have versions. Most don’t. On pages for books that don’t have version. the version drop-down shouldn’t be shown.
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/get-started/welcome-to-prisma-cloud
- After: https://fix-version-dd--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/get-started/welcome-to-prisma-cloud

Fix: Hide version selector when there are no versions

---

blocks/sidenav/sidenav.js
blocks/table/table.css

Update styling for tables without headers and fix left nav arrow styles for lazy loaded books
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-october-2023#new-features1
- After: https://fixes-styling--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-october-2023#new-features1
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-2023
- After: https://fixes-styling--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/rn/prisma-cloud- …

Fixes for table headers and left nav arrow styling

---

blocks/table/table.js
scripts/scripts.js

fix #215
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-oci-account/oci-apis-ingested-by-prisma-cloud?branch=ian-fix-sheets
- After: https://maxed-bugs-3--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-oci-account/oci-apis-ingested-by-prisma-cloud?branch=ian-fix-sheets

fix: handle sheet params in table block

---

scripts/scripts.js

- add warning when `store.mainBook` is undefined, but the page is configured as a `book` template

console warnings

---

blocks/article/article.js

The "Prisma Cloud TechDocs" logo/text in the top left of the article pane should take you to the main landing page.
Test URLs:
- After: https://ian-fix-article-back-home--prisma-cloud-docs-website--hlxsites.hlx.page/

fix: construct working landing page links in articles

---

blocks/sidenav/sidenav.js

The sidenav code added a forward slash (`/`) to the end of URLs in the product spreadsheet. The code should use the URLs as-is from the product spreadsheet
Test URLs:
- After: https://ian-fix-product-switcher--prisma-cloud-docs-website--hlxsites.hlx.page/

fix: properly construct product selector URLs

---

blocks/sidenav/sidenav.js

- Refactor the products spreadsheet - Currently, there's one products sheet system-wide. Instead, use one products sheet per language dir. This way, if only 1 of X products is translated, you can limit what's shown in the product selector drop-down menu. For example, en has three products (Enterprise Edition, Compute Edition, and Classic), but we only translated one product into jp (Enterprise Edition)
- Handle the case when there's only a single product (e.g. jp only has Enterprise Edition). In this case, disable the product drop-down menu. Clicking shouldn't do anything since there aren't any other products to switch to.
Test URLs:
- After: https://ian-products-localization--prisma-cloud-docs-website--hlxsites.hlx.page …

Enhance how products work with localized content

---

scripts/delayed.js
scripts/lib-franklin.js

Enable Adobe Analytics on our site.
Test URLs:
- After: https://ian-analytics-phase1--prisma-cloud-docs-website--hlxsites.hlx.page/

Add Adobe Launch

---

blocks/sidenav/sidenav.css
blocks/sidenav/sidenav.js

Resurrect the ToC filter control in the sidenav (with fixes and tweaks).
Test URLs:
- After: https://ian-filter-nav--prisma-cloud-docs-website--hlxsites.hlx.page/

Add ToC filter

---

blocks/article/article.css
blocks/article/article.js

Add the ability to show an optional announcement banner at the top of any page. The banner is configurable via the metadata sheet.
In the metadata sheet, there's an announcement column. If the page being rendered has an announcement (an HTML string), the string is taken from the metadata and rendered in a red box at the top of the page.
There aren't many configuration options for announcements yet. The goal was to get this out as quickly as possible because we have old pages that customers still mistakenly reference, but which PM isn't ready to pull down yet. We want to able to quickly redirect customers to the right place.
Fix #<gh-issue-id>
Test URLs:
- After: …

Add optional announcement banner

---

blocks/article/article.css

Numbered listed and nested numbered lists aren't styled when ingested from Gdocs. Numbered lists count from in integers startingfrom 1. Nested numbered lists (all levels) also count in integers starting from 1. Level 1 nesting should count in lowercase alpha. Level 2 nesting should count in lowercase roman numerals.
Test URLs:
- After: https://ian-style-numbered-lists--prisma-cloud-docs-website--hlxsites.hlx.page/

Style numbered lists in articles

---

blocks/search-bar/search-bar.css

Currently, there is no relevant CSS rule for dark mode, and the highlighted bits of the search suggestions aren't visible. This commit adds explicit rules.
Test URLs:
- After: https://ian-fix-search-suggestions--prisma-cloud-docs-website--hlxsites.hlx.page/

Adds CSS for highlighted text in search suggestions
