- helix-query.yaml
- helix-sitemap.yaml
- sitemap-index.xml
Test URLs:
Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/sitemap-index.xml
After: https://maxed-sitemap--prisma-cloud-docs-website--hlxsites.hlx.page/sitemap-index.xml
> fix: add sitemap stuff

- scripts/lib-franklin.js
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/admin-guide-pcee/access-control/rbac
- After: https://update-franklin-lib--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/admin-guide-pcee/access-control/rbac
> update franklin lib

- blocks/footer/footer.css
- blocks/footer/footer.js
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/30-xx/admin-guide/access-control/rbac
- After: https://maxed-footer--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/30-xx/admin-guide/access-control/rbac
> fix footer style

- blocks/article/article.js
- blocks/sidenav/sidenav.css
- blocks/sidenav/sidenav.js
- scripts/scripts.js
- styles/styles.css
- types/Store.d.ts
- version picker, based on @icaraps `versions` branch
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/access-control/rbac
- After: https://maxed-versions--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/access-control/rbac
> version picker changes

- blocks/article/article.js
- scripts/scripts.js
- types/Store.d.ts
Fix #18
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/welcome/getting-started
- After: https://maxed-redirect-article--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/welcome/getting-started
> redirect to first topic on missing article

- blocks/cards/cards.css
- blocks/cards/cards.js
- scripts/scripts.js
- styles/styles.css
* cards
* yt video
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/16
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en
- After: https://product-landing--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en
> product landing

- styles/styles.css
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/configure/custom-feeds
- After: https://link-color--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/configure/custom-feeds
> update default link color

- 404.html
- blocks/breadcrumbs/breadcrumbs.css
- blocks/breadcrumbs/breadcrumbs.js
- blocks/cards/cards.css
- blocks/header/header.css
- blocks/hero-search/hero-search.css
- blocks/hero-search/hero-search.js
- blocks/product-tiles/product-tiles.css
- blocks/product-tiles/product-tiles.js
- blocks/table/table.css
- blocks/table/table.js
- scripts/scripts.js
- styles/styles.css
Fix #25 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en
- After: https://maxed-landing--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en
> division landing page

- prisma/prisma-cloud/blocks/article/article.js
- prisma/prisma-cloud/blocks/sidenav/sidenav.css
- prisma/prisma-cloud/blocks/sidenav/sidenav.js
- prisma/prisma-cloud/styles/favicon.svg
- prisma/prisma-cloud/styles/styles.css
Fix #45 
fix #44 
fix #43 
fix #41 
fix #40 
fix #39 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/30-xx/admin-guide/install/install-onebox
- After: https://maxed-fixes--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/30-xx/admin-guide/install/install-onebox
> various fixes

- prisma/prisma-cloud/blocks/article/article.js
- prisma/prisma-cloud/blocks/sidenav/sidenav.js
- prisma/prisma-cloud/scripts/scripts.js
Fix #50
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide
- After: https://maxed-fixes--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide
> more fixes

- prisma/prisma-cloud/scripts/scripts.js
Fix #53 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/access-control/rbac?branch=ian-add-file
- After: https://branch-search-param-v2--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/access-control/rbac?branch=ian-add-file
Click on Prisma Cloud Operationalize Guide > Phases > Test and you should land on a page with test content
> support navigation with branch search param

- fstab.yaml
Fix #57
Test URLs:
- After: https://issue-57--prisma-cloud-docs-website--hlxsites.hlx.page/
> fix: add folder mapping for other products

- prisma/prisma-cloud/blocks/article/article.js
- prisma/prisma-cloud/scripts/scripts.js
ref: #72 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/test_sitemap?branch=ian-ol4
- After: https://issue-72--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/test_sitemap?branch=ian-ol4
> try cache reload on branched urls

- prisma/prisma-cloud/blocks/article/article.css
- prisma/prisma-cloud/blocks/article/article.js
Fix #59
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide
- After: https://issue-59--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide
> fix: render some article content on 404s

- prisma/prisma-cloud/blocks/sidenav/sidenav.js
Fix #61
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-defender/install-single-container-defender
- After: https://issue-61--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-defender/install-single-container-defender
> fix: expanding nested lists

- prisma/prisma-cloud/blocks/sidenav/sidenav.css
- prisma/prisma-cloud/blocks/sidenav/sidenav.js
Fix #62
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-defender/install-single-container-defender
- After: https://issue-62--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-defender/install-single-container-defender
> fix: scroll current topic in sidenav

- helix-query.yaml
- helix-sitemap.yaml
- sitemap-index.xml
> sitemap tweaks

- prisma/prisma-cloud/blocks/article/article.js
- prisma/prisma-cloud/scripts/scripts.js
Fix #69
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/timeline?branch=ian-sitemap
- After: https://fix-preview-images--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/timeline?branch=ian-sitemap
> fix preview images

- prisma/prisma-cloud/blocks/article/article.js
- prisma/prisma-cloud/scripts/scripts.js
Fix #69 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/timeline?branch=test-preview-image
- After: https://fix-preview-images-v2--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/timeline?branch=test-preview-image
> fix missing branch search param for preview images

- prisma/prisma-cloud/blocks/sidenav/sidenav.js
Fix #63
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide
- After: https://issue-63--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide
> fix: insert adjacent to last list in sidenav

- prisma/prisma-cloud/blocks/sidenav/sidenav.css
- prisma/prisma-cloud/blocks/sidenav/sidenav.js
ref #80
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/public-sector/release-findings/release-findings
- After: https://issue-90--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/public-sector/release-findings/release-findings
> fix: nested sidenav items, more selective hiding

- prisma/prisma-cloud/blocks/article/article.js
- prisma/prisma-cloud/blocks/breadcrumbs/breadcrumbs.js
- prisma/prisma-cloud/blocks/sidenav/sidenav.js
- prisma/prisma-cloud/scripts/scripts.js
- types/Article.d.ts
- types/Events.d.ts
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-aws
- After: https://spa-nav--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-aws
> add spa navigation for sidenav

- prisma/prisma-cloud/blocks/article/article.js
Fix #60
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide
- After: https://spa-not-found--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide
> fix: spa nav first chapter to article

- prisma/prisma-cloud/scripts/scripts.js
- types/Events.d.ts
- types/Store.d.ts
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/getting-started
- After: https://blocks-loaded--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/getting-started
> add blocks:loaded store event

- prisma/prisma-cloud/blocks/sidenav/sidenav.js
Fix #102 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/timeline
- After: https://toc-expansion--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/timeline
> fix: toc expansion

- prisma/prisma-cloud/blocks/article/article.js
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-defender/config-app-embedded-fs-protection
- After: https://maxed-fixes--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-defender/config-app-embedded-fs-protection
> fix: scroll to top on spa nav

- prisma/prisma-cloud/blocks/table/table.js
- prisma/prisma-cloud/blocks/toc/toc.css
- prisma/prisma-cloud/blocks/toc/toc.js
- prisma/prisma-cloud/scripts/scripts.js
Fix #116 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/30-xx/admin-guide/configure/permissions?branch=ian-gsheet
- After: https://toc--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/30-xx/admin-guide/configure/permissions?branch=ian-gsheet
> add toc block

- prisma/prisma-cloud/blocks/fragment/fragment.js
Fix #117 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/welcome/launch?branch=ian-complex-gdoc
- After: https://fragment-multi-section--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/welcome/launch?branch=ian-complex-gdoc
> fix fragment multi section doc

- prisma/prisma-cloud/scripts/scripts.js
Fix #121
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/drafts/maxed/no-icons-in-code
- After: https://issue-121--prisma-cloud-docs-website--hlxsites.hlx.page/drafts/maxed/no-icons-in-code
> replace icons in code with their text

- prisma/prisma-cloud/blocks/table/table.js
fix #132 
fix #133
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-windows#feature-matrix
- After: https://maxed-fixes-2--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-windows#feature-matrix
related pr: https://github.com/hlxsites/prisma-cloud-docs/pull/73
> table block fixes

- fstab.yaml
Add product/book
Test URLs:
- After: https://<branch>--prisma-cloud-docs-website--hlxsites.hlx.page/
> Add Prisma Cloud (CSPM) Admin Guide product/book

- fstab.yaml
Stage stand-alone legacy RQL Ref bok
Test URLs:
- After: https://ian-add-product2--prisma-cloud-docs-website--hlxsites.hlx.page/
> Add legacy product/book: RQL Ref

- prisma/prisma-cloud/blocks/sidenav/sidenav.js
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/classic/cspm-admin-guide?branch=ian%2Fclassic
- After: https://maxed-fixes-3--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/classic/cspm-admin-guide?branch=ian%2Fclassic
> fix: handle nested topics

- fstab.yaml
Clean up unused products
Test URLs:
- After: https://ian-del-prods--prisma-cloud-docs-website--hlxsites.hlx.page/
> Delete code-security and cns products

- fstab.yaml
Prep staging site
Test URLs:
- After: https://ian-rename-compute-prod--prisma-cloud-docs-website--hlxsites.hlx.page/
> Rename product: compute -> compute-edition

- fstab.yaml
Test URLs:
- After: https://ian-ee--prisma-cloud-docs-website--hlxsites.hlx.page/
> Rename product: cspm -> enterprise-edition

- prisma/prisma-cloud/blocks/article/article.js
fix #158
Test URLs:
Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/use-cases/visibility-control/visibility-control
After: https://maxed-fixes-2--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/use-cases/visibility-control/visibility-control
> fix: load theme toggle as custom element

- sitemap-index.xml
ref: #183 
see also: https://github.com/hlxsites/prisma-cloud-docs/pull/109
> fix: update sitemap-index

- blocks/article/article.css
- blocks/article/article.js
- blocks/fragment/fragment.js
- blocks/sidenav/sidenav.js
- scripts/scripts.js
- types/Article.d.ts
- types/Store.d.ts
- types/globals.d.ts
Fix #170 
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition
- After: https://maxed-gdoc-articles--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition
- After: https://maxed-gdoc-articles--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections
- After: https://maxed-gdoc-articles--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/use-cases/secure-the-infrastructure/secure-the-infrastructure
> gdoc articles

- blocks/card-carousel/card-carousel.css
- blocks/header/header.css
- blocks/header/header.js
- blocks/hero-search/hero-search.js
- blocks/search-bar/search-bar.css
- blocks/search-bar/search-bar.js
- styles/styles.css
- types/Events.d.ts
- defer loading coveo until needed
- fix CLS issues
Test URLs:
- After: https://maxed-perf--prisma-cloud-docs-website--hlxsites.hlx.page/en
- After: https://maxed-perf--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition
- After: https://maxed-perf--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections
- After: https://maxed-perf--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/use-cases/secure-the-source/risk-prevention
> performance fixes

- blocks/article/article.js
- blocks/card-carousel/card-carousel.css
- styles/styles.css
Test URLs:
- After: https://maxed-imgs--prisma-cloud-docs-website--hlxsites.hlx.page/en
- After: https://maxed-imgs--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/get-started/prisma-cloud-platform
> fix: overflows, article img srcs, img dimensions

- blocks/hero-search/hero-search.css
- blocks/hero-search/hero-search.js
- blocks/search-bar/search-bar.js
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en
- After: https://maxed-cls-2--prisma-cloud-docs-website--hlxsites.hlx.live/en
> fix: cls issues on homepage

- blocks/article/article.js
- scripts/scripts.js
Fix #221
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/application-security/get-started/application-security-license-types
- After: https://maxed-img-tweaks--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/application-security/get-started/application-security-license-types
> fix: article image search params

- blocks/resources/resources.js
Simulate pulling data from RSS feed from local file.
Test URLs:
- After: https://ian-tmp-fix-front-page--prisma-cloud-docs-website--hlxsites.hlx.page/
> Fix Resources section on front page

- blocks/footer/footer.css
- blocks/footer/footer.js
- blocks/header/header.css
- blocks/header/header.js
- blocks/latest-releases/latest-releases.js
- blocks/resources/resources.js
- blocks/search-bar/search-bar.css
- blocks/search-bar/search-bar.js
- robots.txt
- scripts/scripts.js
- styles/styles.css
Test URLs:
- After: https://maxed-scores--prisma-cloud-docs-website--hlxsites.hlx.page/en
> improve PSI scores

- blocks/card-carousel/card-carousel.js
- blocks/resources/resources.js
Test URLs:
- After: https://maxed-scores--prisma-cloud-docs-website--hlxsites.hlx.page/en
> fix: a11y workaround for splide

- blocks/resources/resources.css
- blocks/resources/resources.js
Test URLs:
- After: https://maxed-scores-2--prisma-cloud-docs-website--hlxsites.hlx.page/en
> iso: more 100s

- blocks/resources/resources.js
Test URLs:
- After: https://maxed-scores-2--prisma-cloud-docs-website--hlxsites.hlx.page/en
> fix: dont block on card render in resources block

- blocks/article/article.css
- blocks/article/article.js
- blocks/search-bar/search-bar.js
- blocks/sidenav/sidenav.js
- blocks/theme-toggle/theme-toggle.js
- scripts/scripts.js
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.hlx.page//en/enterprise-edition/content-collections/get-started/adoption-advisor
- After: https://maxed-scores-2--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/get-started/adoption-advisor
> lighthouse improvements for article pages

- blocks/fragment/fragment.js
Fix issue with images in fragments not loading.
Fix #235 
Test URLs:
- After: https://iansk-fragment-imgs--prisma-cloud-docs-website--hlxsites.hlx.page/
> fix: add docs prefix to img src paths in fragments

- sitemap-index.xml
Test URLs:
- After: https://ian-update-sitemap-index--prisma-cloud-docs-website--hlxsites.hlx.page/
> Update sitemap-index for Japanese content

- blocks/article/article.css
- blocks/article/article.js
- blocks/search-bar/search-bar.js
- blocks/sidenav/sidenav.js
- blocks/theme-toggle/theme-toggle.js
- scripts/scripts.js
Reverts hlxsites/prisma-cloud-docs-website#231
> Revert "lighthouse improvements for article pages"

- scripts/lib-franklin.js
Test URLs:
- After: https://rum-updates--prisma-cloud-docs-website--hlxsites.hlx.page/
> fix(rum): update samplerum fn

- google9c06ff42c01d7a20.html
Test URLs:
- After: https://ian-google-search-console--prisma-cloud-docs-website--hlxsites.hlx.page/
> Verify site to enable access to Google Search Console

- scripts/delayed.js
Test URLs:
- After: https://ian-add-google-analytics--prisma-cloud-docs-website--hlxsites.hlx.page/
> Add Google Analytics

- .github/pull_request_template.md
- README.md
- scripts/scripts.js
ref: https://github.com/hlxsites/prisma-cloud-docs/pull/1078
Test URLs:
- Before: https://main--prisma-cloud-docs-website--hlxsites.aem.page/
- After: https://v5--prisma-cloud-docs-website--hlxsites.aem.page/
> feat: upgrade to v5

- .github/pull_request_template.md
- README.md
- scripts/scripts.js
Reverts hlxsites/prisma-cloud-docs-website#250
> Revert "feat: upgrade to v5"
